version: '3.8'
services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - discovery.type=single-node
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600

  opensearch-dashboard:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboard
    ports:
      - 5601:5601

  logstash:
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:latest
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./mysql-connector-java-5.1.49/mysql-connector-java-5.1.49.jar:/usr/share/logstash/mysql-connector-java-5.1.49/mysql-connector-java-5.1.49.jar
    environment:
      - opensearch_host=opensearch
    depends_on:
      - opensearch

volumes:
  opensearch-data: